### ISSUE TITLE
Not Generating PDFs

### ISSUE THREAD

**Issue by Marrionetta** [Dejauxvue/YGOProxyGenerator#12]
I've used this many times in the past but suddenly it's been about 2 days from what i noticed, I've pushed generate PDF at least 40 times over the last two days and nothing would happen even after an hour.

**Comment by Dejauxvue** [comment]
I tried it today and it worked with a small example.
Can you test it again with you decklist and provide your input here, if it's still not working?

**Comment by Marrionetta** [comment]
I'll give it a shot when I get home and will let you know.

**Comment by Marrionetta** [comment]
Yeah it works now. Strange. Thanks anyway~
