### ISSUE TITLE
Good proxy maker, but no feedback on issues

### ISSUE THREAD

**Issue by sentrywiz** [Dejauxvue/YGOProxyGenerator#13]
I like the YGO proxy maker, easy to use, good. But in many times it gets stuck because maybe a card name was entered wrongly, or it just doesn't give me any pdf until after refreshing the page. A small window for displaying errors might be useful

**Comment by Dejauxvue** [comment]
I think, we had this feature before. I don't know, where it went. I'll have a look into it this week.

**Comment by Dejauxvue** [comment]
Done. Can you double check and close the issue, if it works?

**Comment by sentrywiz** [comment]
I could do one idea, based on how much javascript+PHP you know. For PHP I'd help out, but I've not experiemented with the YGOPro API. 

1. [3 Cyber Dragon](https://db.ygoprodeck.com/card/?search=Cyber+Dragon)
2. 3 Cyber End Dragon

When I put newline, the API could read the name, and put the name in a link to YGOPRO website. It would probably require some sort of AJAX functionality with the API. Not sure if you even want to code it.
