### ISSUE TITLE
Site fails to get info for all cards?

### ISSUE THREAD

**Issue by ramirostUW** [Dejauxvue/YGOProxyGenerator#14]
Not sure if this is a new problem, but whenever I use the website now, either by dropping a ydk or typing a card name, the website fails to get the info to generate a proxy. Even something like Mudora fails. 

I don't think it's a problem with the API, it seems to retrieve card info just fine at the moment (tested this equivalent call : https://db.ygoprodeck.com/api/v7/cardinfo.php?name=Mudora)

**Comment by ramirostUW** [comment]
Upon further investigation, it seems to be a CORS issue

**Comment by Dejauxvue** [comment]
thanks for the report.
I will look into it tomorrow

**Comment by Dejauxvue** [comment]
The problem seems a bit more complicated. I need to find a new source for the images since ygoprodeck does not allow accessing the images via API

**Comment by ramirostUW** [comment]
I'm sorry to hear that. Maybe try emailing the guy from ygoprodeck? This site shouldn't be too much of a strain on his servers, maybe he can whitelist it

**Comment by Dejauxvue** [comment]
should be working again :)
this site got whitelisted for the API
