### ISSUE TITLE
could not process the following lines

### ISSUE THREAD

**Issue by soulking9** [Dejauxvue/YGOProxyGenerator#15]
ive been using this for about half a year now i cant afford to buy actual cards and i always made proxy cards using this site. yesterday and today i tried to make some but every time i try and make any i keep getting a message saying could not process the folowwing lines then it downloads a pdf with nothing on it just a blank page. at first i thought maybe ocg cards didint work but i even tried to proxy a GOAT format deck and i got the same issue

**Comment by Dejauxvue** [comment]
good to hear that this project helps you to play ygo on a budget :)
This issue is duplicate to #14 . For updates, look there
