### ISSUE TITLE
[Request] Can you add a functionality to change the document size from Letter to A4?

### ISSUE THREAD

**Issue by elijah0067** [Dejauxvue/YGOProxyGenerator#18]
I noticed that there doesn't seem to be an option to change the document from Letter to A4 size. I would appreciate it if you could add that functionality in the future. Thanks.

**Comment by Dejauxvue** [comment]
Good catch, never realized that myself 
Can you try if it works now? Remeber to reload your cache with ctrl + f5

**Comment by elijah0067** [comment]
I have reviewed the card sizes and confirm they are accurate for both letter and A4 paper. Thank you for your prompt response.
