### ISSUE TITLE
Paper Size

### ISSUE THREAD

**Issue by lukaajnstajn** [Dejauxvue/YGOProxyGenerator#20]
it's always in a page  9  cards in a 3*3 scale, even in A3 and A5. I thought that it would fit all of the paper that could and will not go through the paper 
![image](https://github.com/Dejauxvue/YGOProxyGenerator/assets/17624560/22f68033-bbce-46dc-8cce-f812c3018540)
A5  size
![image](https://github.com/Dejauxvue/YGOProxyGenerator/assets/17624560/be0c20cf-0e72-4b16-af3e-379b3f7f8ad4)
A3 size

**Comment by Dejauxvue** [comment]
should be fixed now, thank your very much for the report!
