### ISSUE TITLE
custom database

### ISSUE THREAD

**Issue by leyth7** [Dejauxvue/YGOProxyGenerator#25]
great work brother, can i suggest that you can change the database from which the cards are taken, because for example i speak arabic, and i got a folder of 12000 yugioh cards translated in arabic, and want your ygoproxygenerator to use my folder to pick the yugioh cards to print. i hope u take that into consideration cuz it will help a lot of us middle easterners, thank in advance brother.

**Comment by Dejauxvue** [comment]
I think the best way is to fork the repository locally on your PC and adjust the API call manually. Unfortunately the API-calls do not translate very well local file structures, so you would have to do the most work yourself...
currently not a planned feature. 
best wishes to you and I hope you'll find a solution
