### ISSUE TITLE
Unit of Margin

### ISSUE THREAD

**Issue by LErikson42** [Dejauxvue/YGOProxyGenerator#26]
I don't see any informations regarding the unit of the margin. If I try to use 40 millimeters it's something like 14 mm?
A tool tip for the margin would be helpful.

**Comment by Dejauxvue** [comment]
thanks for the feedback. I added a tooltip. the unit is "pdfpoint" which is 1/72 inch (more info: https://pdfkit.org/docs/getting_started.html)
