### ISSUE TITLE
10th Card is cut off, and one card not found

### ISSUE THREAD

**Issue by Studious-dude** [Dejauxvue/YGOProxyGenerator#5]
I attempted to create the following decklist, but the pdf cutoff all images after number 9. Additionally, the following card was not found: 42566602 (Coral Dragon)

`35261759
35261759
35261759
49088914
49088914
49088914
08736823
08736823
08736823
49966326
49966326
49966326
25311006
25311006
25311006
50275295
50275295
50275295
14558127
14558127
14558127
13364097
13364097
13364097
86483512
86483512
86483512
82732705
70368879
12571621
12571621
12571621
14886190
14886190
14886190
49036338
67723438
38814750
38814750
38814750
88581108
88581108
42566602
87188910
92519087
35252119
91949988
62709239
09348522
64880894
66698383
90448279
21521304
90664857
38495396
27204311
27204311
27204311
18144506
43898403
43898403
23002292
82385847
43534808
43534808
43534808
58655504
58655504
58655504
61740673`

Downloaded PDF appeared as such
[download.pdf](https://github.com/Dejauxvue/YGOProxyGenerator/files/5599614/download.pdf)

**Comment by Dejauxvue** [comment]
sorry that it took so long
can you test again with the current website?`
