### ISSUE TITLE
On Default Settings, Cards are Smaller than the Original

### ISSUE THREAD

**Issue by MarkDeuerling** [Dejauxvue/YGOProxyGenerator#9]
With default settings, the printed proxy  size is a bit smaller than the original card size. Especially in height it is less high than the original, but the width is a bit smaller, too.
I think in width it should be 2-3px more and in heigh idk maybe 10-15px or so.
This has been an issure (I think) after #8  was closed.

**Comment by Dejauxvue** [comment]
adjusted the scaling. I couldn't find proper documentation of image scaling for pdftoolkit, so the current state is based on measuring with a ruler

**Comment by MarkDeuerling** [comment]
Idk if the cards size is different for regions. In the EU the measurements are 59 x 86 mm (metric system). Also on print, the size may vary, too (for example different paper sizes A4 vs Latter).

**Comment by Dejauxvue** [comment]
Have you tried it with the new scaling?

**Comment by MarkDeuerling** [comment]
Now the printed cards are a bit too big with default settings.

**Comment by Dejauxvue** [comment]
Well it was 1/72 before and then it was too small.
Thank you for your interest in the project and testing.
If you want to, you can try out different values or maybe you find out, what the correct scaling is and submit a pull request?

**Comment by Dejauxvue** [comment]
closed with #10
